from fedora:32

RUN dnf update -y && dnf install -y make gcc gcc-c++ git findutils file file-devel python2 python3
RUN git clone https://github.com/bats-core/bats-core.git && cd bats-core && ./install.sh /usr/local
