from ubuntu:xenial

RUN useradd --no-log-init -r tmpu

RUN apt update -y && apt install -y make gcc g++ git file libmagic-dev python python3 software-properties-common &&\
    add-apt-repository -y ppa:nnstreamer/ppa && apt update -y && apt install -y libiniparser libiniparser-dev googletest cmake
RUN git clone https://github.com/bats-core/bats-core.git && cd bats-core && ./install.sh /usr/local
