from centos:7

RUN useradd --no-log-init -r tmpu

# bats installation
RUN yum update -y && yum install -y make gcc gcc-c++ git file file-devel python2 python3 which\
    iniparser iniparser-devel valgrind
RUN git clone https://github.com/bats-core/bats-core.git && cd bats-core && ./install.sh /usr/local

# coreutils installation
RUN yum install -y automake gettext-devel bison patch rsync wget gperf texinfo

# google test installation
RUN yum install -y epel-release
RUN yum install -y gtest gtest-devel

RUN git clone https://github.com/coreutils/coreutils.git && cd coreutils \
    && git checkout tags/v8.25 && ./bootstrap && FORCE_UNSAFE_CONFIGURE=1 ./configure && make && make install

RUN yum install ruby
RUN gem install bashcov