from ubuntu:xenial

RUN useradd --no-log-init -r tmpu

RUN apt update -y && apt install -y make gcc g++ git file libmagic-dev python python3 software-properties-common &&\
    add-apt-repository -y ppa:nnstreamer/ppa && apt update -y && apt install -y libiniparser libiniparser-dev libgtest-dev cmake valgrind
RUN cd /usr/src/gtest/ && cmake -DBUILD_SHARED_LIBS=ON && make && cp *.so /usr/lib
RUN git clone https://github.com/bats-core/bats-core.git && cd bats-core && ./install.sh /usr/local
