from ubuntu:bionic

RUN useradd --no-log-init -r tmpu

RUN apt update -y && apt install -y make gcc g++ git file libmagic-dev python python3 libiniparser1 libiniparser-dev &&\
    ln -s /usr/include/iniparser/iniparser.h /usr/include/iniparser.h
RUN git clone https://github.com/bats-core/bats-core.git && cd bats-core && ./install.sh /usr/local
