from centos:7

# bats installation
RUN yum update -y && yum install -y make gcc gcc-c++ git 
RUN git clone https://github.com/bats-core/bats-core.git && cd bats-core && ./install.sh /usr/local

# coreutils installation
RUN yum install automake gettext-devel bison patch rsync wget gperf texinfo -y

RUN git clone https://github.com/coreutils/coreutils.git && cd coreutils \
    && git checkout tags/v8.25 && ./bootstrap && FORCE_UNSAFE_CONFIGURE=1 ./configure && make && make install