from centos:6

RUN useradd --no-log-init -r tmpu

RUN yum update -y && yum install -y make gcc gcc-c++ git file file-devel python which
RUN git clone https://github.com/bats-core/bats-core.git && cd bats-core && ./install.sh /usr/local
