from centos:6

RUN useradd --no-log-init -r tmpu

RUN yum update -y && yum install -y make gcc gcc-c++ git file file-devel python which valgrind &&\
    rpm -hiv http://repo.iotti.biz/CentOS/6/x86_64/iniparser-3.1-2.el6.lux.1.x86_64.rpm &&\
    rpm -hiv http://repo.iotti.biz/CentOS/6/x86_64/iniparser-devel-3.1-2.el6.lux.1.x86_64.rpm

RUN yum install -y epel-release && yum install -y gtest gtest-devel

RUN git clone https://github.com/bats-core/bats-core.git && cd bats-core && ./install.sh /usr/local

RUN yum install ruby
RUN gem install bashcov