# image to get sea library and binaries from
FROM ghcr.io/valhayot/sea-xenial:master AS sea

# base image
FROM nipreps/fmriprep:20.2.1

RUN mkdir /sea
COPY --from=sea /libsea/build/sea.so /sea/sea.so
COPY --from=sea /libsea/bin/sea* /bin/

ENV SEA_HOME /sea

RUN echo "#!/bin/bash\n" \
	"export LD_PRELOAD=/sea/sea.so\n" \
	"fmriprep \$@" > /bin/seafprep.sh
RUN chmod +x /bin/seafprep.sh

ENTRYPOINT ["/bin/sea_launch.sh", "/bin/seafprep.sh"]


