FROM fedora:43

RUN useradd --no-log-init -r tmpu

RUN dnf update -y && dnf install -y make gcc gcc-c++ git findutils file file-devel python2 python3 which iniparser iniparser-devel gtest gtest-devel valgrind 
RUN git clone https://github.com/bats-core/bats-core.git && cd bats-core && ./install.sh /usr/local

RUN mkdir /libsea
ADD . /libsea
RUN cd /libsea && make clean && make