on: [push]
name: Docker Tests

jobs:
  install-docker:
    runs-on: ubuntu-20.04
    name: Install Docker
    steps:
      - run: sudo apt update -y && sudo apt-get install -y curl lsb_release
      - run: curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh ./get-docker.sh
      - run: sudo docker run hello-world

    

