on: [push]
name: Docker Tests

jobs:
  install-docker:
    runs-on: ubuntu-latest
    name: Install Docker
    steps:
      - run: sudo apt-get install -y ca-certificates curl gnupg lsb-release
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - run: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
                   $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - run: sudo apt-get update -y && sudo apt-get install docker-ce docker-ce-cli containerd.io

    

